# pylint: skip-file
"""
Se agrego una columna de prueba para el deploy automatico

Revision ID: 0d19a492cbc8
Revises: b46bff422020
Create Date: 2023-11-21 12:12:11.128806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0d19a492cbc8"
down_revision: Union[str, None] = "b46bff422020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("columna_prueba", sa.Boolean(), nullable=False, server_default="1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "columna_prueba")
    # ### end Alembic commands ###
