"""se pone autoincremental el id de likes

Revision ID: 0fd55a0249d0
Revises: 5a43bd2e1dec
Create Date: 2023-09-30 13:38:56.603823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd55a0249d0'
down_revision: Union[str, None] = '5a43bd2e1dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('likes', 'id')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
