# pylint: skip-file
"""
Se agrego la columna de Blocked, esta indica si el usuario fue bloqueado de la aplicacion o no

Revision ID: 230e0cb3cef3
Revises: 081a7e821186
Create Date: 2023-09-29 11:14:53.000002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "230e0cb3cef3"
down_revision: Union[str, None] = "081a7e821186"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("blocked", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "blocked")
    # ### end Alembic commands ###
