# pylint: skip-file
"""agregamos tablas de posts, likes y hashtags

Revision ID: 2f5a0ebd6f23
Revises: 5caf6a945f4d
Create Date: 2023-10-19 23:51:48.877051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f5a0ebd6f23"
down_revision: Union[str, None] = "5caf6a945f4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
