# pylint: skip-file
"""tabla de tokes de expo notification para notificaciones push

Revision ID: 30ee20199668
Revises: f07e4ca60e6e
Create Date: 2023-11-06 22:39:37.243789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30ee20199668"
down_revision: Union[str, None] = "f07e4ca60e6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_tokens",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("device_token", sa.String(500), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("user_id", "device_token", name="uq_user_device_token"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device_tokens")
    # ### end Alembic commands ###
