# pylint: skip-file
"""Se agregan las tablas de Repost y Hashtag, la columna is_public de post y se cambia el largo del string en las columnas content e image de post

Revision ID: 79f97b454224
Revises: b4fab464ea2d
Create Date: 2023-10-12 17:02:22.928438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79f97b454224"
down_revision: Union[str, None] = "b4fab464ea2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "content", type_=sa.String(length=1000))
    op.alter_column("posts", "image", type_=sa.String(length=1000))

    op.create_table(
        "reposts",
        sa.Column("id_post", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id_post", "user_id"),
    )

    op.create_table(
        "hashtags",
        sa.Column("id_post", sa.Integer(), nullable=False),
        sa.Column("hashtag", sa.String(length=75), nullable=False),
        sa.PrimaryKeyConstraint("id_post", "hashtag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "is_public")
    op.alter_column("posts", "content", type_=sa.String(length=800))
    op.alter_column("posts", "image", type_=sa.String(length=800))
    # ### end Alembic commands ###
