# pylint: skip-file
"""agrego nuevas tablas (intento 2)

Revision ID: ae9fa2844388
Revises: 8aca63428a6b
Create Date: 2023-10-05 14:49:32.673800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ae9fa2844388"
down_revision: Union[str, None] = "8aca63428a6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
