# pylint: skip-file
"""se agrega tabla de favoritos

Revision ID: c8dcfc5cf795
Revises: eb6c9fecc802
Create Date: 2023-11-17 22:05:59.502673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8dcfc5cf795"
down_revision: Union[str, None] = "eb6c9fecc802"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Crea la tabla "favorites"
    op.create_table(
        "favorites",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), default=sa.func.now(), nullable=True),
        sa.UniqueConstraint("user_id", "content_id"),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.content_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("content_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favorites")
    # ### end Alembic commands ###
