# pylint: skip-file
"""se crea la tabla de tokens para login con datos biometricos

Revision ID: eaa861baac9d
Revises: c8dcfc5cf795
Create Date: 2023-11-23 18:28:00.078806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eaa861baac9d"
down_revision: Union[str, None] = "c8dcfc5cf795"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "biometric_tokens",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("biometric_token", sa.String(500), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.UniqueConstraint(
            "user_id", "biometric_token", name="uq_user_biometric_token"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("biometric_tokens")
    # ### end Alembic commands ###
