# pylint: skip-file

"""
Se saco la columna, ya funciona el deploy automatico en elephant.

Revision ID: eb6c9fecc802
Revises: 0d19a492cbc8
Create Date: 2023-11-21 12:39:58.752603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "eb6c9fecc802"
down_revision: Union[str, None] = "0d19a492cbc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "columna_prueba")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "columna_prueba",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
