# pylint: skip-file
"""se crea la tabla de menciones

Revision ID: f07e4ca60e6e
Revises: 4150ca75ac2e
Create Date: 2023-11-02 20:42:09.448575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f07e4ca60e6e"
down_revision: Union[str, None] = "4150ca75ac2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mentions",
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column("user_mention_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), default=sa.func.now(), nullable=True),
        sa.UniqueConstraint("user_mention_id", "content_id"),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.content_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_mention_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("content_id", "user_mention_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mentions")
    # ### end Alembic commands ###
