name: Code Coverage Check

on:
  push:
  pull_request:

jobs:
  Coverage-Check:
    runs-on: ubuntu-latest
    # Postgres instance for testing:
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests with Coverage
      run: |
        export DB_URI="postgresql://exoiymmb:4HyrnUG6vFsTwmhIG_B_N6j2NdyKMt5s@motty.db.elephantsql.com:5432/exoiymmb"
        coverage run -m pytest tests/test_posts.py

    - name: Generate Coverage Report
      run: |
        coverage report -m

    - name: Check Coverage
      run: |
        COVERAGE_THRESHOLD="80"
        LAST_COVERAGE=$(coverage report -m | grep -oP '\d+%' | tail -n 1)
        if [[ "$LAST_COVERAGE" < "$COVERAGE_THRESHOLD" ]]; then
          echo "Code coverage is less than $COVERAGE_THRESHOLD%"
          exit 1
        fi